### ISSUE TITLE
Branching that isn't needed

### ISSUE THREAD

**Issue by StoneCypher** [Ehawk82/Ehawk82-TicTacToe#15]
[So here you have a thing](https://github.com/Ehawk82/Tic-Tac-Toe/blob/master/docs/src/js/scripts.js#L102)

```javascript
			if(player === "X"){
				td.innerHTML = "X";
				player = "O";
			} else if(player === "O"){
				td.innerHTML = "O";
				player = "X";
			}
```

This can be done without if

The `innerHTML` can be a straight assignment

You can get the reversal for `player` with `?:`

I don't know if you've seen ternary `?:` before.

```javascript
const reverse = (side === "heads")? "tails" : "heads";

const acceptable = (drink === "coffee")? true : false;
```

**Comment by Ehawk82** [comment]
I'm not sure if I understand how to implement this technique properly. Could you provide some more tips to help me interpret this process.

**Comment by Ehawk82** [comment]
not sure if I have this right or not, but knowing how to use it, that is another story...

<code>
const thingy = (player === "X")? "O" : "X";
</code>

**Comment by StoneCypher** [comment]
that's correct

the way ternary works is it evaluates the first term, then it'll return the second if truthy, or the third if falsey
